version: '3'
services:
    apache:
        build: .docker/apache
        container_name: nicolas_goncalves_apache
        ports:
          - ${DOCKER_APACHE_PORT}:80
        volumes:
          - .docker/config/vhosts:/etc/apache2/sites-enabled
          - .:/var/www/dealabs
          - .docker/data/apache:/var/log/apache2
        environment:
          PHP_IDE_CONFIG: serverName=dealabs.docker
        depends_on:
          - php

    php:
        build: .docker/php
        container_name: nicolas_goncalves_php
        volumes:
          - .:/var/www/dealabs
        environment:
          - mailcatcher_host=nicolas_goncalves_mailcatcher
        depends_on:
          - mailcatcher

    mailcatcher:
        container_name: nicolas_goncalves_mailcatcher
        restart: on-failure:10
        image: dockage/mailcatcher:0.7.1
        ports:
            - ${DOCKER_MAILCATCHER_1_PORT}:1080
            - ${DOCKER_MAILCATCHER_2_PORT}:1025

    mysql:
        image: mysql:5.7
        command: ['--default-authentication-plugin=mysql_native_password']
        container_name: nicolas_goncalves_mysql
        volumes:
            - .docker/data/db:/var/lib/mysql
        ports:
            - "${DOCKER_MYSQL_PORT}:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: dealabs
            MYSQL_USER: dealabs
            MYSQL_PASSWORD: dealabs

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: nicolas_goncalves_phpmyadmin
        environment:
          PMA_HOST: mysql
          PMA_PORT: 3306
        ports:
            - ${DOCKER_PHPMYADMIN_PORT}:80
        links:
            - mysql
